import { type Static, type TSchema, Type } from "typebox";
import { Check, Errors } from "typebox/value";

const HOST_ID_PATTERN =
  "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$";

export const HostIdSchema = Type.String({ pattern: HOST_ID_PATTERN });
export type HostId = Static<typeof HostIdSchema>;

export const JsonValueSchema = Type.Cyclic(
  {
    JsonValue: Type.Union([
      Type.Null(),
      Type.Boolean(),
      Type.Number(),
      Type.String(),
      Type.Array(Type.Ref("JsonValue")),
      Type.Record(Type.String(), Type.Ref("JsonValue")),
    ]),
  },
  "JsonValue"
);
export type JsonValue = Static<typeof JsonValueSchema>;

export const HostHealthSchema = Type.Object(
  {
    capabilities: Type.Array(Type.String()),
    hostId: HostIdSchema,
    ok: Type.Literal(true),
    protocolVersion: Type.Integer({ minimum: 1 }),
    version: Type.Integer({ minimum: 1 }),
  },
  { additionalProperties: false }
);
export type HostHealth = Static<typeof HostHealthSchema>;

/**
 * Client-local Host registry contracts.
 *
 * A Host is the execution owner and never learns about this registry. A
 * registry belongs to one client (CLI profile, Electron userData, browser
 * localStorage, ...); different clients are not synchronized. Entry ids are
 * generated by the client and stay stable across connections. They are
 * deliberately a different concept from the Host health `hostId`, which is
 * the persistent identity of a Host installation/data directory
 * (`server/host-identity.cjs` stores it in `host.json`). It survives Host
 * process restarts, so restarting a Host is not an identity mismatch.
 *
 * Registry entries contain routing and display data only. Bearer tokens and
 * other credential material are never part of this schema; `credentialRef` is
 * an opaque pointer to whatever platform credential store the client uses.
 */
export const HOST_REGISTRY_SCHEMA = "omo.host-registry";
export const HOST_REGISTRY_VERSION = 1;

const REGISTRY_ENTRY_ID_PATTERN = "^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$";

export const HostRegistryEntryIdSchema = Type.String({
  pattern: REGISTRY_ENTRY_ID_PATTERN,
});
export type HostRegistryEntryId = Static<typeof HostRegistryEntryIdSchema>;

export const HttpHostEndpointSchema = Type.Object(
  { transport: Type.Literal("http"), url: Type.String({ minLength: 1 }) },
  { additionalProperties: false }
);
export type HttpHostEndpoint = Static<typeof HttpHostEndpointSchema>;

export const HttpsHostEndpointSchema = Type.Object(
  { transport: Type.Literal("https"), url: Type.String({ minLength: 1 }) },
  { additionalProperties: false }
);
export type HttpsHostEndpoint = Static<typeof HttpsHostEndpointSchema>;

export const UnixHostEndpointSchema = Type.Object(
  { path: Type.String({ minLength: 1 }), transport: Type.Literal("unix") },
  { additionalProperties: false }
);
export type UnixHostEndpoint = Static<typeof UnixHostEndpointSchema>;

export const NamedPipeHostEndpointSchema = Type.Object(
  { path: Type.String({ minLength: 1 }), transport: Type.Literal("pipe") },
  { additionalProperties: false }
);
export type NamedPipeHostEndpoint = Static<typeof NamedPipeHostEndpointSchema>;

export const HostEndpointSchema = Type.Union([
  HttpHostEndpointSchema,
  HttpsHostEndpointSchema,
  UnixHostEndpointSchema,
  NamedPipeHostEndpointSchema,
]);
export type HostEndpoint = Static<typeof HostEndpointSchema>;

const HOST_REGISTRY_ENTRY_PROPERTIES = {
  credentialRef: Type.Optional(Type.String({ minLength: 1 })),
  endpoint: HostEndpointSchema,
  expectedHostId: Type.Optional(HostIdSchema),
  id: HostRegistryEntryIdSchema,
  label: Type.String({ minLength: 1 }),
} as const;

export const HostRegistryEntrySchema = Type.Object(
  HOST_REGISTRY_ENTRY_PROPERTIES,
  { additionalProperties: false }
);
export type HostRegistryEntry = Static<typeof HostRegistryEntrySchema>;

export const HostRegistryDocumentSchema = Type.Object(
  {
    entries: Type.Array(HostRegistryEntrySchema),
    schema: Type.Literal(HOST_REGISTRY_SCHEMA),
    selectedEntryId: Type.Optional(HostRegistryEntryIdSchema),
    version: Type.Literal(HOST_REGISTRY_VERSION),
  },
  { additionalProperties: false }
);
export type HostRegistryDocument = Static<typeof HostRegistryDocumentSchema>;

export const OkResponseSchema = Type.Object(
  { ok: Type.Literal(true) },
  { additionalProperties: false }
);
export type OkResponse = Static<typeof OkResponseSchema>;

export const ProjectSchema = Type.Object(
  {
    cwd: Type.String({ minLength: 1 }),
    id: Type.String({ minLength: 1 }),
    name: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type Project = Static<typeof ProjectSchema>;

export const ProjectListSchema = Type.Array(ProjectSchema);
export type ProjectList = Static<typeof ProjectListSchema>;

export const AddProjectCommandSchema = Type.Object(
  {
    cwd: Type.String({ minLength: 1 }),
    name: Type.Optional(Type.String({ minLength: 1 })),
  },
  { additionalProperties: false }
);
export type AddProjectCommand = Static<typeof AddProjectCommandSchema>;

export const SessionSummarySchema = Type.Object(
  {
    allMessagesText: Type.Optional(Type.String()),
    created: Type.Number(),
    cwd: Type.String(),
    firstMessage: Type.String(),
    id: Type.String({ minLength: 1 }),
    messageCount: Type.Optional(Type.Integer({ minimum: 0 })),
    modified: Type.Number(),
    name: Type.Optional(Type.String()),
    parentSessionPath: Type.Optional(Type.String({ minLength: 1 })),
    path: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type SessionSummary = Static<typeof SessionSummarySchema>;

export const SessionListQuerySchema = Type.Object(
  { cwd: Type.String({ minLength: 1 }) },
  { additionalProperties: false }
);
export type SessionListQuery = Static<typeof SessionListQuerySchema>;

export const SessionListSchema = Type.Array(SessionSummarySchema);
export type SessionList = Static<typeof SessionListSchema>;

export const OpenSessionCommandSchema = Type.Object(
  {
    cwd: Type.String({ minLength: 1 }),
    sessionId: Type.String({ minLength: 1 }),
    sessionPath: Type.Optional(Type.String({ minLength: 1 })),
  },
  { additionalProperties: false }
);
export type OpenSessionCommand = Static<typeof OpenSessionCommandSchema>;

export const ContextUsageSchema = Type.Object(
  {
    contextWindow: Type.Number({ minimum: 0 }),
    percent: Type.Union([Type.Number({ minimum: 0 }), Type.Null()]),
    tokens: Type.Union([Type.Number({ minimum: 0 }), Type.Null()]),
  },
  { additionalProperties: false }
);
export type ContextUsage = Static<typeof ContextUsageSchema>;

export const SessionModelSchema = Type.Object(
  {
    id: Type.String({ minLength: 1 }),
    name: Type.String({ minLength: 1 }),
    provider: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type SessionModel = Static<typeof SessionModelSchema>;

export const SessionOutlineItemSchema = Type.Object(
  {
    absoluteIndex: Type.Integer({ minimum: 0 }),
    id: Type.String({ minLength: 1 }),
    userPreview: Type.String(),
  },
  { additionalProperties: true }
);
export type SessionOutlineItem = Static<typeof SessionOutlineItemSchema>;

export const OpenSessionResponseSchema = Type.Object(
  {
    contextUsage: Type.Union([ContextUsageSchema, Type.Null()]),
    cursor: Type.Integer({ minimum: 0 }),
    eventSequence: Type.Integer({ minimum: 0 }),
    hasMore: Type.Boolean(),
    isStreaming: Type.Boolean(),
    messages: Type.Array(JsonValueSchema),
    model: Type.Union([SessionModelSchema, Type.Null()]),
    outline: Type.Optional(Type.Array(SessionOutlineItemSchema)),
    replayFromSequence: Type.Optional(Type.Integer({ minimum: 0 })),
    sessionFile: Type.Optional(Type.String({ minLength: 1 })),
    sessionId: Type.String({ minLength: 1 }),
    thinkingLevel: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type OpenSessionResponse = Static<typeof OpenSessionResponseSchema>;

export const ImageAttachmentSchema = Type.Object(
  {
    data: Type.String({ maxLength: 8_000_000 }),
    mimeType: Type.String({ pattern: "^image/" }),
    type: Type.Literal("image"),
  },
  { additionalProperties: false }
);
export type ImageAttachment = Static<typeof ImageAttachmentSchema>;

export const PromptCommandSchema = Type.Object(
  {
    cwd: Type.Optional(Type.String({ minLength: 1 })),
    images: Type.Optional(Type.Array(ImageAttachmentSchema, { maxItems: 8 })),
    message: Type.String({ minLength: 1 }),
    requestId: Type.String({ minLength: 1 }),
    sessionId: Type.String({ minLength: 1 }),
    sessionPath: Type.Optional(Type.String({ minLength: 1 })),
  },
  { additionalProperties: false }
);
export type PromptCommand = Static<typeof PromptCommandSchema>;

export const AbortCommandSchema = Type.Object(
  {
    sessionId: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type AbortCommand = Static<typeof AbortCommandSchema>;

export const AcceptedOperationSchema = Type.Object(
  {
    operationId: Type.String({ minLength: 1 }),
    sessionFile: Type.Optional(Type.String({ minLength: 1 })),
    sessionId: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type AcceptedOperation = Static<typeof AcceptedOperationSchema>;

export const AgentEventEnvelopeSchema = Type.Object(
  {
    id: Type.String({ minLength: 1 }),
    payload: JsonValueSchema,
    sequence: Type.Integer({ minimum: 1 }),
    sessionId: Type.String({ minLength: 1 }),
    timestamp: Type.Number(),
    type: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type AgentEventEnvelope = Static<typeof AgentEventEnvelopeSchema>;

export const EventStreamQuerySchema = Type.Object(
  {
    after: Type.Optional(Type.Integer({ minimum: 0 })),
    sessionId: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type EventStreamQuery = Static<typeof EventStreamQuerySchema>;

export const HostApiContracts = {
  abortSession: {
    body: AbortCommandSchema,
    method: "POST",
    path: "/api/v1/pi/abort",
    response: OkResponseSchema,
  },
  addProject: {
    body: AddProjectCommandSchema,
    method: "POST",
    path: "/api/v1/projects",
    response: ProjectSchema,
  },
  health: {
    method: "GET",
    path: "/api/v1/health",
    response: HostHealthSchema,
  },
  listProjects: {
    method: "GET",
    path: "/api/v1/projects",
    response: ProjectListSchema,
  },
  listSessions: {
    method: "GET",
    path: "/api/v1/sessions",
    query: SessionListQuerySchema,
    response: SessionListSchema,
  },
  openSession: {
    body: OpenSessionCommandSchema,
    method: "POST",
    path: "/api/v1/pi/open",
    response: OpenSessionResponseSchema,
  },
  prompt: {
    body: PromptCommandSchema,
    method: "POST",
    path: "/api/v1/pi/prompt",
    response: AcceptedOperationSchema,
  },
  sessionEvents: {
    event: AgentEventEnvelopeSchema,
    method: "GET",
    path: "/api/v1/events",
    query: EventStreamQuerySchema,
  },
} as const;

/**
 * Extension private channel contracts (docs/extension-daemon-hybrid.md §5).
 *
 * These endpoints are mounted ONLY on the daemon's loopback Unix socket /
 * Windows named pipe listener, never on the public TCP/TLS listener. Every
 * request except `register` authenticates with the short-lived instance
 * credential returned by `register`, transported as an
 * `Authorization: Bearer <credential>` header. The credential is never part
 * of any JSON body, event payload, log line, or Session JSONL, and the
 * public Bearer Token is never written into Extension configuration.
 *
 * Fencing rules (design §4/§5):
 *
 * - A daemon issues a monotonically increasing `generation` per accepted
 *   attachment of one Session. Only the latest generation is valid; requests
 *   carrying a stale `(instanceId, generation)` pair are rejected.
 * - Native events are deduplicated on `(instanceId, generation,
 *   nativeSequence)` before being mapped onto the existing Host event
 *   `sequence`; clients only ever observe the Host sequence.
 * - Commands are deduplicated on `(instanceId, generation, commandSequence)`
 *   and by `requestId`; an ack is correlated by `requestId` and echoes the
 *   command's `commandSequence`.
 * - `nativeSequence` is monotonic per Extension process and restarts at 1 on
 *   every process start; it is meaningless without its `(instanceId,
 *   generation)` scope.
 */
export const EXTENSION_CHANNEL_VERSION = 1;

export const ExtensionInstanceIdSchema = Type.String({
  pattern: HOST_ID_PATTERN,
});
export type ExtensionInstanceId = Static<typeof ExtensionInstanceIdSchema>;

export const ExtensionGenerationSchema = Type.Integer({ minimum: 1 });
export type ExtensionGeneration = Static<typeof ExtensionGenerationSchema>;

export const ExtensionNativeSequenceSchema = Type.Integer({ minimum: 1 });
export type ExtensionNativeSequence = Static<
  typeof ExtensionNativeSequenceSchema
>;

export const ExtensionCommandSequenceSchema = Type.Integer({ minimum: 1 });
export type ExtensionCommandSequence = Static<
  typeof ExtensionCommandSequenceSchema
>;

export const ExtensionCapabilitySchema = Type.Union([
  Type.Literal("commands"),
  Type.Literal("events"),
]);
export type ExtensionCapability = Static<typeof ExtensionCapabilitySchema>;

export const ExtensionRegisterRequestSchema = Type.Object(
  {
    capabilities: Type.Array(ExtensionCapabilitySchema, { maxItems: 8 }),
    channelVersion: Type.Literal(EXTENSION_CHANNEL_VERSION),
    cwd: Type.Optional(Type.String({ minLength: 1 })),
    extensionVersion: Type.String({ minLength: 1 }),
    instanceId: ExtensionInstanceIdSchema,
    piVersion: Type.String({ minLength: 1 }),
    sessionFile: Type.Optional(Type.String({ minLength: 1 })),
    sessionId: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type ExtensionRegisterRequest = Static<
  typeof ExtensionRegisterRequestSchema
>;

export const ExtensionRegisterAcceptedSchema = Type.Object(
  {
    credential: Type.String({ minLength: 1 }),
    generation: ExtensionGenerationSchema,
    heartbeatIntervalMs: Type.Integer({ minimum: 1000 }),
    heartbeatTimeoutMs: Type.Integer({ minimum: 1000 }),
    hostId: HostIdSchema,
    ok: Type.Literal(true),
  },
  { additionalProperties: false }
);
export type ExtensionRegisterAccepted = Static<
  typeof ExtensionRegisterAcceptedSchema
>;

export const ExtensionRegisterRejectedSchema = Type.Object(
  {
    ok: Type.Literal(false),
    reason: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false }
);
export type ExtensionRegisterRejected = Static<
  typeof ExtensionRegisterRejectedSchema
>;

export const ExtensionRegisterResponseSchema = Type.Union([
  ExtensionRegisterAcceptedSchema,
  ExtensionRegisterRejectedSchema,
]);
export type ExtensionRegisterResponse = Static<
  typeof ExtensionRegisterResponseSchema
>;

export const ExtensionHeartbeatRequestSchema = Type.Object(
  {
    generation: ExtensionGenerationSchema,
    instanceId: ExtensionInstanceIdSchema,
  },
  { additionalProperties: false }
);
export type ExtensionHeartbeatRequest = Static<
  typeof ExtensionHeartbeatRequestSchema
>;

export const ExtensionHeartbeatResponseSchema = Type.Object(
  {
    expiresAt: Type.Number(),
    generation: ExtensionGenerationSchema,
    ok: Type.Literal(true),
  },
  { additionalProperties: false }
);
export type ExtensionHeartbeatResponse = Static<
  typeof ExtensionHeartbeatResponseSchema
>;

export const ExtensionNativeEventSchema = Type.Object(
  {
    event: Type.String({ minLength: 1 }),
    nativeSequence: ExtensionNativeSequenceSchema,
    payload: JsonValueSchema,
    sessionFile: Type.Optional(Type.String({ minLength: 1 })),
    sessionId: Type.String({ minLength: 1 }),
    timestamp: Type.Number(),
  },
  { additionalProperties: false }
);
export type ExtensionNativeEvent = Static<typeof ExtensionNativeEventSchema>;

export const EXTENSION_EVENT_BATCH_MAX_ITEMS = 256;

export const ExtensionEventBatchSchema = Type.Object(
  {
    events: Type.Array(ExtensionNativeEventSchema, {
      maxItems: EXTENSION_EVENT_BATCH_MAX_ITEMS,
    }),
    generation: ExtensionGenerationSchema,
    instanceId: ExtensionInstanceIdSchema,
  },
  { additionalProperties: false }
);
export type ExtensionEventBatch = Static<typeof ExtensionEventBatchSchema>;

export const ExtensionEventBatchResultSchema = Type.Object(
  {
    accepted: Type.Integer({ minimum: 0 }),
    duplicates: Type.Integer({ minimum: 0 }),
    ok: Type.Literal(true),
  },
  { additionalProperties: false }
);
export type ExtensionEventBatchResult = Static<
  typeof ExtensionEventBatchResultSchema
>;

export const ExtensionAckStatusSchema = Type.Union([
  Type.Literal("accepted"),
  Type.Literal("started"),
  Type.Literal("rejected"),
  Type.Literal("completed"),
]);
export type ExtensionAckStatus = Static<typeof ExtensionAckStatusSchema>;

export const ExtensionAckSchema = Type.Object(
  {
    commandSequence: ExtensionCommandSequenceSchema,
    generation: ExtensionGenerationSchema,
    instanceId: ExtensionInstanceIdSchema,
    reason: Type.Optional(Type.String({ minLength: 1 })),
    requestId: Type.String({ minLength: 1 }),
    status: ExtensionAckStatusSchema,
  },
  { additionalProperties: false }
);
export type ExtensionAck = Static<typeof ExtensionAckSchema>;

export const ExtensionPromptCommandSchema = Type.Object(
  {
    commandSequence: ExtensionCommandSequenceSchema,
    requestId: Type.String({ minLength: 1 }),
    text: Type.String({ minLength: 1 }),
    type: Type.Literal("prompt"),
  },
  { additionalProperties: false }
);
export type ExtensionPromptCommand = Static<
  typeof ExtensionPromptCommandSchema
>;

export const ExtensionAbortCommandSchema = Type.Object(
  {
    commandSequence: ExtensionCommandSequenceSchema,
    requestId: Type.String({ minLength: 1 }),
    type: Type.Literal("abort"),
  },
  { additionalProperties: false }
);
export type ExtensionAbortCommand = Static<typeof ExtensionAbortCommandSchema>;

export const ExtensionCommandSchema = Type.Union([
  ExtensionPromptCommandSchema,
  ExtensionAbortCommandSchema,
]);
export type ExtensionCommand = Static<typeof ExtensionCommandSchema>;

export const ExtensionDetachRequestSchema = Type.Object(
  {
    generation: ExtensionGenerationSchema,
    instanceId: ExtensionInstanceIdSchema,
    reason: Type.Optional(Type.String({ minLength: 1 })),
  },
  { additionalProperties: false }
);
export type ExtensionDetachRequest = Static<
  typeof ExtensionDetachRequestSchema
>;

/**
 * Public, credential-free view of who currently executes a Session (design
 * §4). Exposed to Web/Desktop later (E4-001); never carries the instance
 * credential or other process secrets.
 */
export const SessionExecutionStateSchema = Type.Object(
  {
    generation: Type.Optional(ExtensionGenerationSchema),
    ownerInstanceId: Type.Optional(ExtensionInstanceIdSchema),
    state: Type.Union([
      Type.Literal("headless-owned"),
      Type.Literal("native-attached"),
      Type.Literal("detached"),
    ]),
  },
  { additionalProperties: false }
);
export type SessionExecutionState = Static<typeof SessionExecutionStateSchema>;

export const ExtensionChannelContracts = {
  ack: {
    body: ExtensionAckSchema,
    method: "POST",
    path: "/api/v1/extension/ack",
    response: OkResponseSchema,
  },
  commands: {
    event: ExtensionCommandSchema,
    method: "GET",
    path: "/api/v1/extension/commands",
  },
  detach: {
    body: ExtensionDetachRequestSchema,
    method: "POST",
    path: "/api/v1/extension/detach",
    response: OkResponseSchema,
  },
  events: {
    body: ExtensionEventBatchSchema,
    method: "POST",
    path: "/api/v1/extension/events",
    response: ExtensionEventBatchResultSchema,
  },
  heartbeat: {
    body: ExtensionHeartbeatRequestSchema,
    method: "POST",
    path: "/api/v1/extension/heartbeat",
    response: ExtensionHeartbeatResponseSchema,
  },
  register: {
    body: ExtensionRegisterRequestSchema,
    method: "POST",
    path: "/api/v1/extension/register",
    response: ExtensionRegisterResponseSchema,
  },
} as const;

export class ContractValidationError extends Error {
  readonly contract: string;
  readonly issues: readonly string[];

  constructor(contract: string, issues: readonly string[]) {
    super(`Invalid ${contract}: ${issues.join("; ")}`);
    this.name = "ContractValidationError";
    this.contract = contract;
    this.issues = issues;
  }
}

export function parseContract<T extends TSchema>(
  schema: T,
  value: unknown,
  contract: string
): Static<T> {
  if (Check(schema, value)) {
    return value as Static<T>;
  }
  const issues = [...Errors(schema, value)].map((error) => error.message);
  throw new ContractValidationError(contract, issues);
}
